### ISSUE TITLE
v2.3.1 Updating circle...

### ISSUE THREAD

**Issue by bcpi** [appcelerator-modules/ti.map#100]
Hi,

Thanks for adding support for drawing circles on the map!

Is there any way to update the circle once it has been added to the map?  I have a radius slider the user can move to change the radius. I'd like to have the circle on the map to adjust dynamically as the slider is moved.

Any way to do this?

Ti SDK 3.5.1, Ti.map 2.3.1, iOS

Thanks

**Comment by ashcoding** [comment]
Looks like you can do this on Android easily by increasing the radius of the circle
``circ2.radius = circ2.radius +250;``

Doesn't seem to have any effect on iOS.

**Comment by manumaticx** [comment]
I came across this issue too and created a JIRA ticket: https://jira.appcelerator.org/browse/AC-175

**Comment by hansemannn** [comment]
Thx! I just saw the ticket was resolved as invalid, since updating circles at runtime is not supposed to be supported right now. Please feel free to raise a ticket and PR to add this functionality.
