### ISSUE TITLE
Support for Google Maps Business SDK

### ISSUE THREAD

**Issue by deltapoison** [appcelerator-modules/ti.map#101]
If i change the import statements from com.google.android.gms to com.google.android.m4b.maps would i be able to build the module ?

**Comment by ashcoding** [comment]
There's a possibility it might but I think it's good to try and test it out.

I assume you are following the instructions here https://developers.google.com/maps/documentation/business/mobile/android/config where it mentions
```quote
If you have an existing application using Google Play services, replace all references to the com.google.android.gms.maps package with com.google.android.m4b.maps.
```

**Comment by deltapoison** [comment]
I had replaced imports to com.google.android.m4b.maps and added the m4b_libs.jar as library in titanium studio running on titanium-sdk version is 3.5.1.GA. I am facing build issues.

/Users/cybagemac/Documents/map_module/timap/android/src/ti/map/TiUIMapView.java:803: cannot find symbol

    [javac] symbol  : method contains(java.util.ArrayList<ti.map.PolygonProxy>,com.google.android.m4b.maps.model.LatLng)

    [javac] location: class ti.map.Shape.Boundary

    [javac] ArrayList<PolygonProxy> clickedPolygon = boundary.contains(currentPolygons, point);

/Users/cybagemac/Documents/maps_business/ti.map/android/src/ti/map/AnnotationProxy.java:136: cannot find symbol
    [javac] symbol  : class LatLng
    [javac] location: class ti.map.AnnotationProxy
    [javac] 		LatLng position = new LatLng(latitude, longitude);

**Comment by hansemannn** [comment]
Please file a JIRA-issue for that, so it's easier to discuss and schedule a fix. Thx!
