### ISSUE TITLE
iOS & ti.map v2.3.1: A few bugs with annotations...

### ISSUE THREAD

**Issue by bcpi** [appcelerator-modules/ti.map#104]
Hi,

I have a map on iOS with a pin annotation on it, that is set to draggable = true.  

1. Whenever I tap on it and start dragging it, it gets dropped automatically a second later without me lifting the finger from the screen (to stop the drag gesture).  So I can only drag it in very small increments over the map canvas. 

2. The  newState value reported by the "pinchangedragstate" event does not seem to report the correct values either.  It goes through 2, 1, 0 values, but never reports 4 (ANNOTATION_DRAG_STATE_END)

3. Lastly, clicksource never returns 'rightButton' on the click event of the map for an annotation with a rightButton defined as Ti.UI.iPhone.SystemButton.DISCLOSURE. So I'm unable to capture any clicks on the annotation's button.

This used to work prior to the 64bit release update, but hasn't work well in the releases since then.

Ti SDK 3.5.1, Ti.map 2.3.1, iOS 8

Thanks!

**Comment by hansemannn** [comment]
Hi @bcpi , we fixed all bugs in the latest iOS version 2.4.1.
