### ISSUE TITLE
Click events don't fire for popups

### ISSUE THREAD

**Issue by iamsteadman** [appcelerator-modules/ti.map#105]
When using the Titanium map module in iOS 8 (it probably happens in earlier versions too), `click` events don't fire for annotation popups.

The view's `click` event fires when you tap the pin itself, but once you tap it and reveal the popup (with title, subtitle, left/right buttons etc), no touch events fire for that popup. This makes the map useless as you can imagine, as you lose the 'list-detail' relationship, and it's not practical to open a detail view when you tap the pin; you need to know what you're tapping first.

I know someone will be temped to say it's about setting the title, or not setting the title, or using `leftView` instead of `leftButton` or using `rightView` instead of `rightButton` or binding to the annotation itself (which has no documented events), but none of these work.

I'm using the `setAnnotation()` method to add the marker, but had tried it via the property before. I'm using 2.3.1 of the module, on the rebranded SDK (4.0).

**Comment by pamik** [comment]
I had same problem. The workaround is to use the previous version 2.2.2.

**Comment by maximcan** [comment]
pamik, it is the good solution for everybody who doesn't use polygons. Is this problem still unsolved ?

**Comment by decklord** [comment]
Having the same issue.

**Comment by dbeth** [comment]
Me too. I have the same problem.

**Comment by maximcan** [comment]
Good news ! Check here : https://jira.appcelerator.org/browse/MOD-1840

**Comment by jfalcone** [comment]
And https://jira.appcelerator.org/browse/TIMOB-19280

This is a huge regression and it impacts our apps severely.  Rolling back to 2.2.2 is the temporary fix.

**Comment by preszedrox** [comment]
We are facing same issue. Do you please send us solution for the same. As in our app we need both the feature : polygon draw as well as on click on annotation.

**Comment by yozef** [comment]
It could be that you have lots of overlays: such as polygons &/or circles &/polylines, the implementation of map click events when these were added creates a loop through all of them killing performance in order to return the overlay that was tapped on. I have compiled my own ti.map to remove these loops, as I did not need in my case to know which overlay was tapped on.

**Comment by darknos** [comment]
I added "hack" for handle click on popup
https://github.com/appcelerator-modules/ti.map/pull/159

**Comment by hansemannn** [comment]
Referring to @darknos' PR #159, thx!
