### ISSUE TITLE
Can't set opacity on Polygons

### ISSUE THREAD

**Issue by blackcatbf** [appcelerator-modules/ti.map#107]
Hi,

It seems that the opacity parameter for Polygons isn't active yet.
It would be great to have this feature implemented to keep map visible behind the polygons.

Thanks

**Comment by FokkeZB** [comment]
You can set the alpha channel for the fillColor or strokeColor to do this: `#8F00`.

**Comment by blackcatbf** [comment]
Sorry to be that stupid... Thanks!
I should have tried this before asking.
