### ISSUE TITLE
TiViewProxy.toImage returns TiBlob, not KrollDict

### ISSUE THREAD

**Issue by grebulon** [appcelerator-modules/ti.map#108]
In `AnnotationProxy.handleCustomView` there's a call to `toImage`, but the return type is wrong.

**Comment by weixingsun** [comment]
I think you may have found out your solution, I changed AnnotationProxy.java in my solution:
		if (obj instanceof TiViewProxy) {
			//KrollDict d = ((TiViewProxy) obj).toImage();
			//Object imageBlob = d.get(TiC.PROPERTY_MEDIA);
			//if (imageBlob instanceof TiBlob) {
			//	Bitmap image = ((TiBlob) imageBlob).getImage();
			TiBlob imageBlob = ((TiViewProxy) obj).toImage();
				Bitmap image = imageBlob.getImage();
				if (image != null) {
					markerOptions.icon(BitmapDescriptorFactory.fromBitmap(image));
					setIconImageHeight(image.getHeight());
					return;
				}
			//}
		}

**Comment by hansemannn** [comment]
@grebulon @weixingsun Can you file an issue so our Android dev's can fix this issue?

**Comment by hansemannn** [comment]
Fixed since Ti.Map Android 4.1.1
