### ISSUE TITLE
Cannot compile with 4.1.0GA and Xcode 6.4

### ISSUE THREAD

**Issue by TonyCat** [appcelerator-modules/ti.map#111]
I'm having issues with the ti.map so i decided to come and see if i can build a new module. I updated my version to 4.1.0 in module.xcconfig to 4.1.0 then tried to do python build.py and it errored out. Opened up the Xcode project and its failing on TiProxy.h (screen shot attached) I'm not sure how to fix that. Can you guys get this build-able again?
![screen shot 2015-07-28 at 11 30 45 am](https://cloud.githubusercontent.com/assets/3309771/8935823/bd814f70-351c-11e5-86ba-54c58eafcfdf.png)

**Comment by hansemannn** [comment]
Hi @TonyCat , can you please try to build the module using Ti.SDK 5.0.0.GA or later?

**Comment by hansemannn** [comment]
Just testing using 5.0.0.GA, 5.0.2.GA and later, the issue was fixed there.
