### ISSUE TITLE
Linker Issue

### ISSUE THREAD

**Issue by ulizama** [appcelerator-modules/ti.map#115]
Building a project on XCode that uses the module gives me the following error:
```
duplicate symbol _VIEW_TYPE_POLYGON in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapAnnotationProxy.o)
duplicate symbol _VIEW_TYPE_CIRCLE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapAnnotationProxy.o)
duplicate symbol _VIEW_TYPE_POLYLINE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapAnnotationProxy.o)
duplicate symbol _VIEW_TYPE_POLYGON in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapImageAnnotationView.o)
duplicate symbol _VIEW_TYPE_CIRCLE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapImageAnnotationView.o)
duplicate symbol _VIEW_TYPE_POLYLINE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapImageAnnotationView.o)
duplicate symbol _VIEW_TYPE_POLYGON in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapIOS7View.o)
duplicate symbol _VIEW_TYPE_CIRCLE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapIOS7View.o)
duplicate symbol _VIEW_TYPE_POLYLINE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapIOS7View.o)
duplicate symbol _VIEW_TYPE_POLYGON in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapPinAnnotationView.o)
duplicate symbol _VIEW_TYPE_CIRCLE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapPinAnnotationView.o)
duplicate symbol _VIEW_TYPE_POLYLINE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapPinAnnotationView.o)
duplicate symbol _VIEW_TYPE_POLYGON in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapIOS7ViewProxy.o)
duplicate symbol _VIEW_TYPE_CIRCLE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapIOS7ViewProxy.o)
duplicate symbol _VIEW_TYPE_POLYLINE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapIOS7ViewProxy.o)
duplicate symbol _VIEW_TYPE_POLYGON in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapUtils.o)
duplicate symbol _VIEW_TYPE_CIRCLE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapUtils.o)
duplicate symbol _VIEW_TYPE_POLYLINE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapUtils.o)
duplicate symbol _VIEW_TYPE_POLYGON in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapView.o)
duplicate symbol _VIEW_TYPE_CIRCLE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapView.o)
duplicate symbol _VIEW_TYPE_POLYLINE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapView.o)
duplicate symbol _VIEW_TYPE_POLYGON in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapViewProxy.o)
duplicate symbol _VIEW_TYPE_CIRCLE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapViewProxy.o)
duplicate symbol _VIEW_TYPE_POLYLINE in:
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapCustomAnnotationView.o)
    /Users/ulizama/Library/Application Support/Titanium/modules/iphone/ti.map/2.3.2/libti.map.a(TiMapViewProxy.o)
ld: 24 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm using SDK 4.1.0.GA and version 2.3.2 of the module.

**Comment by pilosof** [comment]
any hack found to solve this ?

**Comment by madmanlear** [comment]
Having the same issue on two other Appcelerator builds, both running 4.1.0 GA, but only after opening the Xcode profile file.

**Comment by yozef** [comment]
Having the exact same issue. Been trying to use Instruments to profile the Ti app from XCode, however ti.map is throwing "clang: error: linker command failed with exit code 1 (use -v to see invocation)"

**Comment by hansemannn** [comment]
Hi together, we fixed that issue in the early September, can you recheck this issue?

**Comment by gabrielperales** [comment]
I'm having this issue. I have tried with **Xcode 6.1** and Titanium SDK `4.0` and `4.1` with some differents `ti.map` versions like *2.3.1* and *2.5.2*. I also know I did it run last november... but I can't remember which titanium setup I had, but it should be pretty similar to which I have now... and I'm using the same laptop...

This is the Xcode output:

> Ld Build/Products/Debug-iphonesimulator/Corre.app/Corre normal x86_64
    cd "/Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/build/iphone"
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/cex/.nvm/versions/node/v0.12.9/bin:/usr/local/share/npm/bin/bin:/Users/cex/mongodb/bin:/Users/cex/android-sdk-macosx/platform-tools:/Users/cex/android-sdk-macosx/tools:/Users/cex/ImageMagick-6.8.9/bin:/Users/cex/bin/Sencha/Cmd/5.0.0.160:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/share/npm/bin:/usr/X11/bin:/usr/local/git/bin:/Users/cex/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -L/Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto\ Corre/build/iphone/Build/Products/Debug-iphonesimulator -L/Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto\ Corre/build/iphone/lib -L/Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto\ Corre/modules/iphone/ti.map/2.5.2 -L/Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto\ Corre/modules/iphone/analytics.google/3.1.0 -L/Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto\ Corre/modules/iphone/dk.napp.social/1.7.9 -L/Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto\ Corre/build/iphone/Classes/APSAnalytics -L/Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto\ Corre/build/iphone/Classes/APSHTTPClient -F/Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto\ Corre/build/iphone/Build/Products/Debug-iphonesimulator -filelist /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto\ Corre/build/iphone/Build/Intermediates/Corre.build/Debug-iphonesimulator/Corre.build/Objects-normal/x86_64/Corre.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -ObjC -weak_framework Social -weak_framework Accounts -weak_framework Social -weak_framework Accounts -framework CoreData -framework CoreData -weak_framework MapKit -weak_framework MapKit -weak-lti_ios_profiler -weak-lti_ios_debugger -weak-lTiCore -fobjc-link-runtime -Xlinker -no_implicit_dylibs -stdlib=libc++ -mios-simulator-version-min=7.0 -weak_framework iAd -framework CoreMedia -weak_framework CoreMotion -lAPSAnalytics -weak_framework CoreText -framework EventKit -framework EventKitUI -weak_framework Security -licucore -framework Foundation -weak_framework UIKit -framework CoreGraphics -weak_framework AddressBook -framework AddressBookUI -framework CFNetwork -framework CoreLocation -weak_framework MapKit -framework MessageUI -framework MobileCoreServices -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -lsqlite3 -lz -framework AudioToolbox -weak_framework MediaPlayer -framework AVFoundation -lxml2 -lAPSHTTPClient -ltiverify -lti.map -lanalytics.google -ldk.napp.social -Xlinker -dependency_info -Xlinker /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto\ Corre/build/iphone/Build/Intermediates/Corre.build/Debug-iphonesimulator/Corre.build/Objects-normal/x86_64/Corre_dependency_info.dat -o /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto\ Corre/build/iphone/Build/Products/Debug-iphonesimulator/Corre.app/Corre

> duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapPolylineProxy.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapPolylineProxy.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModuleAssets.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModuleAssets.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapAnnotationProxy.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapAnnotationProxy.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapCustomAnnotationView.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapCustomAnnotationView.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapRouteProxy.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapRouteProxy.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapPolygonProxy.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapPolygonProxy.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapCameraProxy.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapCameraProxy.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(WildcardGestureRecognizer.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(WildcardGestureRecognizer.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapImageAnnotationView.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapImageAnnotationView.o)
> duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapIOS7View.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapIOS7View.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapPinAnnotationView.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapPinAnnotationView.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapIOS7ViewProxy.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapIOS7ViewProxy.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapCircleProxy.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapCircleProxy.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapUtils.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapUtils.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapView.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapView.o)
duplicate symbol _llvm.cmdline in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapViewProxy.o)
duplicate symbol _llvm.embedded.module in:
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapModule.o)
    /Users/cex/Documents/Appcelerator_Studio_Workspace/Proyecto Corre/modules/iphone/ti.map/2.5.2/libti.map.a(TiMapViewProxy.o)
ld: 32 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hansemannn** [comment]
@gabrielperales Please try with Xcode 7.x, since Xcode 6.x support will officially be dropped next months in favor of the iOS 9 API's that require Xcode >= 7.0. If the issue is still present on latest the Xcode, feel free to file an issue on [JIRA](https://jira.appcelerator.org)

**Comment by gabrielperales** [comment]
@hansemannn Ok, thank you very much for your answer, I could did it run with the Titanium SDK 3.5 and ti.map 2.2.0, so I'm going to keep working with this setup. If I have more troubles, I will update it to Xcode 7.x.
