### ISSUE TITLE
Module not working in china

### ISSUE THREAD

**Issue by parweensingh** [appcelerator-modules/ti.map#126]
Hey, this module is working in our app for the entire world with an exception of "CHINA". Kindly,Provide an alternative way to make this work in china.Thanks.

**Comment by parweensingh** [comment]
To add, The maps are not working only on android.

**Comment by hansemannn** [comment]
Hi @parweensingh , can you open a ticket on jira.appcelerator.org and provide a log so we can reproduce your issue? We are very interested in fixing your issues.

**Comment by parween** [comment]
Hi @hansemannn ,Thanks a lot for the response but I don't have log for the same. I will get the app tested in china and share the log obtained via analytics. Will that serve the purpose? Also, Can I go ahead and open a ticket without log? Thanks.

**Comment by hansemannn** [comment]
A log is necessary for us to reproduce your issue. Can you receive the debug log when running the app on the device? That is possible using CLI: "appc ti build -p ios -T device" or using the Appcelerator Studio.

**Comment by parween** [comment]
Hi @hansemannn ,Yes,I can obtain the debug log but I am not able to replicate the issue as I am in India.I have sent a sample app to china to get it tested by a user and will get back to you with the logs obtained via google analytics.Also, Kindly suggest if there is some better way to obtain the log. Thanks Again for the interest shown. Shall keep you posted with the developments.

To add on,

Google maps services are banned in china.But, google does provide an alternative.
![screen shot 2015-11-04 at 1 05 30 pm](https://cloud.githubusercontent.com/assets/11163980/10932123/fea1c21c-82f3-11e5-9c9b-ed2fa663e50f.png)

So based on the current location we can open google maps for china (i.e. maps.google.cn) if the user is in china & open default google maps(i.e. maps.google.com) for the rest of the world.Can this be achieved using this module?

Also, Ti.Geolocation doesn't work in china so we have fallen back to ArrowDb to obtain the current location.

**Comment by hansemannn** [comment]
Cleaning up our Github issues, since engineers usually follow JIRA tickets for this kind of stuff. Please file a JIRA-issue for that, so it's easier to discuss and schedule a fix. Thx!
