### ISSUE TITLE
Adding new Features to Ti.Map for Android (titanium.jar not found)

### ISSUE THREAD

**Issue by yozef** [appcelerator-modules/ti.map#132]
I am trying to add the option of enabling/disabling the Level Picker for Indoor Locations [Level Picker for Indoor Locations](https://developers.google.com/android/reference/com/google/android/gms/maps/UiSettings#setIndoorLevelPickerEnabled(boolean))

1- I update `src/ti.map/TiUIMapView.java` with: 
~~~
line: 195
public void processMapProperties(KrollDict d) {
...
    if (d.containsKey(MapModule.PROPERTY_ENABLE_LEVEL_PICKER)) {
	setCompassEnabled(TiConvert.toBoolean(d,
	   MapModule.PROPERTY_ENABLE_LEVEL_PICKER, true));
    }
}
~~~
then in:
~~~
public void propertyChanged(String key, Object oldValue, Object newValue,
			KrollProxy proxy) {
   .... line 276
    else if (key.equals(TiC.PROPERTY_ENABLE_LEVEL_PICKER)) {
	  setLevelPickerEnabled(TiConvert.toBoolean(newValue, true));
     }

... a little futher down, I add:
protected void setLevelPickerEnabled(boolean enabled) {
	map.getUiSettings().setIndoorLevelPickerEnabled(enabled);
}
~~~

then in `ViewProxy.java`:
~~~
line 30:
TiC.PROPERTY_ENABLE_LEVEL_PICKER, MapModule.PROPERTY_ENABLE_LEVEL_PICKER,
~~~

Everywhere I add TiC.PROPERTY_ENABLE_LEVEL_PICKER, I get the red line under it, as it is not defined in `TiC.class`

Now the issue I am facing is... I cannot access `TiC.class` in order to add `PROPERTY_ENABLE_LEVEL_PICKER`

I get this when I click on TiC.class: Source not found - The Jar File .../titanium.jar has no source source attachement.

I take the gamble of adding it from /TiSDK/.../android/titanium.jar ... yet nothing happens.

Below is my project file structure:
<img width="329" alt="screen shot 2015-10-28 at 8 29 25 am" src="https://cloud.githubusercontent.com/assets/287256/10788491/4e95e8da-7d4e-11e5-990b-76a4e4a2c288.png">

**Comment by yozef** [comment]
For now I have managed to hardcode:
~~~
map.getUiSettings().setIndoorLevelPickerEnabled(false);
~~~

However it would be interesting for other to use this param as well.

**Comment by ashcoding** [comment]
To add to TiC, you would need to do a PR to https://github.com/appcelerator/titanium_mobile/blob/master/android/titanium/src/java/org/appcelerator/titanium/TiC.java and add it here and then compile the module with the new SDK.

Instead, for this scenario, I think adding a property in MapModule will suffice. 
https://github.com/appcelerator-modules/ti.map/blob/master/android/src/ti/map/MapModule.java
You can add 
```java
public static final String PROPERTY_ENABLE_LEVEL_PICKER = "enableLevelPicker";
```
From there, you can refer to it as written in your code as `MapModule.PROPERTY_ENABLE_LEVEL_PICKER`
