### ISSUE TITLE
Add Support for addTileOverlay

### ISSUE THREAD

**Issue by rlarmore** [appcelerator-modules/ti.map#139]
It would be helpful to create custom titles that overlay the existing ones. Please see gmaps documentation here.

https://developers.google.com/android/reference/com/google/android/gms/maps/model/TileOverlay

For IOS MKTileOverlay
https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKTileOverlay_class/

**Comment by hansemannn** [comment]
Please follow #136 and [MOD-2173](https://jira.appcelerator.org/browse/MOD-2173) to track the process of this feature.
