### ISSUE TITLE
indoor maps support.

### ISSUE THREAD

**Issue by MangeshVyas** [appcelerator-modules/ti.map#142]
Good work. Work with most of the requirements. Can we extent this to support indoor maps ? 
is this already support indoor maps ? Any help will be appricaite..

**Comment by yozef** [comment]
Support for Indoor Maps comes out of the box with CoreLocation on iOS (and Titanium returns you the location event with the floor level). However with Apple & Google (much tougher crowd to deal with) is to Survey the area you would like this accuracy indoors.

**Comment by hansemannn** [comment]
Hi @MangeshVyas, please file a [JIRA-ticket](http://jira.appcelerator.org) regarding your feature request. Thanks!

**Comment by hansemannn** [comment]
Closing this issue, since the floorLebel can already be received.
