### ISSUE TITLE
Supressing of Google navigation

### ISSUE THREAD

**Issue by AppWerft** [appcelerator-modules/ti.map#143]
In newest Android Version I see after annotation clicking navi elements from Google. How can I supress?

**Comment by ashcoding** [comment]
Could you add code and a screenshot to illustrate this issue?

**Comment by AppWerft** [comment]
![screenshot_2016-01-11-09-35-51](https://cloud.githubusercontent.com/assets/2996237/12229871/8736b6a8-b843-11e5-801c-9bfafc4a767d.png)

**Comment by ashcoding** [comment]
Create a jira ticket for this https://jira.appcelerator.org/browse/MOD-2189. Seems like we need to have `setMapToolbarEnabled(false)` to disable/surpress that.

**Comment by AppWerft** [comment]
Thanks for JIRA ticket

**Comment by ashcoding** [comment]
Do you have a simple app.js code that I could run to produce that navigation element?
Also, which android version and device are you using?

**Comment by AppWerft** [comment]
SDK 5.1.1.GA / Android23

Simple window with mapview in it: https://github.com/AppWerft/Tierstimmenarchiv/blob/master/Resources/ui/map.window.js

**Comment by ashcoding** [comment]
[ti.map-android-2.3.7.zip](https://github.com/appcelerator-modules/ti.map/files/88306/ti.map-android-2.3.7.zip)

I am unable (for the moment) to produce that navi icons. Attached above is a test version (not final release) that has the property `mapToolbarEnabled`. Set it to false.

Eg:
```
Map.createView({
            region : {
                latitude : 13,
                longitude : 10,
                latitudeDelta : 130,
                longitudeDelta : 130
            },
            mapType : Map.TERRAIN_TYPE,
            enableZoomControls : false,
            compassEnabled : false,
            userLocation : false,
            userLocationButton : false,
            mapToolbarEnabled : false
        });
```

If it works for you, that would be great. Let me know.

**Comment by AppWerft** [comment]
Now it works, great! Thanks for your quick answer and help!

**Comment by ashcoding** [comment]
I'll add this module to the official release and Jira ticket.

**Comment by ashcoding** [comment]
Closing issue.

**Comment by ashcoding** [comment]
https://github.com/appcelerator-modules/ti.map/releases/tag/android-2.3.7
