### ISSUE TITLE
Implement regionWillChangeAnimated on iOS

### ISSUE THREAD

**Issue by yozef** [appcelerator-modules/ti.map#145]
It would be nice to implement this event trigger on iOS:
```- (void)mapView:(MKMapView *)mapView regionWillChangeAnimated:(BOOL)animated```

We do have ```regionDidChangeAnimated``` in ti.map for iOS & Android, however ```regionWillChangeAnimated``` is just as good to have :)

**Comment by hansemannn** [comment]
Hi @yozef, sounds reasonable! Can you file a JIRA-ticket so we can track the issue? Would you like a new event like `regionwillchange` to be triggered before the existing `regionchanged` event?

**Comment by yozef** [comment]
Definitely that is the behavior intended. Thx @hansemannn 
I actually tried implementing it myself, however, I got a red screen within my Ti App, with several tries :/

Jira: https://jira.appcelerator.org/browse/AC-581

**Comment by hansemannn** [comment]
Great! Just moved your ticket to the MOD namespace and implemented the feature in https://github.com/appcelerator-modules/ti.map/pull/146. Also added
[ti.map-iphone-2.7.0.zip](https://github.com/appcelerator-modules/ti.map/files/104910/ti.map-iphone-2.7.0.zip) here to test it. Will also test it today, feedback appreciated!

**Comment by yozef** [comment]
Will test it out now :)
Thanks so much!!!

**Comment by hansemannn** [comment]
Just tested it using the following code, working fine for me:
```javascript
var window = Ti.UI.createWindow();
var Map = require("ti.map");
var mapView = Map.createView();
 
mapView.addEventListener("regionwillchange", function(e) {
  Ti.API.warn("Region will change now!");
  Ti.API.warn(e);
});
 
mapView.addEventListener("regionchanged", function(e) {
  Ti.API.warn("Region did change!");
  Ti.API.warn(e);
});
 
window.add(mapView);
window.open();
```

**Comment by yozef** [comment]
Works great :)
