### ISSUE TITLE
Calling .toImage() on the map view gives blank image

### ISSUE THREAD

**Issue by garycrook** [appcelerator-modules/ti.map#147]
I'm trying to get a blob of the map view by calling .toImage(), but results in a black image with 'Google' in the bottom left corner. Any fixes for this?

**Comment by ashcoding** [comment]
@garycrook Is this for Android or iOS? And could you give more information? Thanks!

**Comment by garycrook** [comment]
Sorry, it's for Android. I've set up all of the Google Maps API key etc. and the map is showing in the app.

`app.ui.map = require('ti.map');`
...
`var mapView = app.ui.map.createView({`
`   mapType: app.ui.map.SATELLITE_TYPE,`
`   userLocation: true,`
`   animate: true,`
`   regionFit: true`
`});`
...
`var mapContainerView = Ti.UI.createView({});`
`mapContainerView.add(mapView); // Other Ti views get added to mapContainerView as overlays` 
..
`win.add(mapContainerView);`
..
`var imageBlob = mapView.toImage();`

When saved out to a file or the blob is passed straight to an ImageView, it's just a blank image with 'Google' in the bottom left corner. It hasn't captured the actual map into the bitmap.

**Comment by wsliaw** [comment]
Hi, for Android, you have to do like this:

```
mapView.addEventListener('onsnapshotready', function(e) {
	var imageBlob = e.snapshot;
});
```


reference: http://docs.appcelerator.com/platform/latest/#!/api/Modules.Map.View-event-onsnapshotready

**Comment by garycrook** [comment]
Cool, thanks that worked!

**Comment by wsliaw** [comment]
you're welcome ;)

**Comment by ashcoding** [comment]
@wsliaw Great work! :+1:
Closing this. :)

**Comment by TonyCat** [comment]
I can not get toImage to work on IOS its saves the map blank with the word "legal" in the bottom left hand corner and I tried using a callback. Any ideas?
```

var Map = require('ti.map');
var GPSmap = Map.createView({
				mapType : Map.SATELLITE_TYPE,
				region : {
					latitude : MYLATITUDE,
					longitude : MYLONGITUDE,
					latitudeDelta : 0.01,
					longitudeDelta : 0.01
				},
				userLocation : false
			});

win.add(GPSmap);

var mapBlob = GPSmap.toImage(function(e){
					var filename = Titanium.Filesystem.applicationDataDirectory + "/tempmap.jpg";
					f = Titanium.Filesystem.getFile(filename);
					f.write(mapBlob);
					
					myimageview.image = Ti.Filesystem.applicationDataDirectory + "/tempmap.jpg"
				});
```

**Comment by garycrook** [comment]
I called it like this on iOS:

var imageBlob = mapView.toImage(null, true); // no immediate callback,
honour scale factor

Then processed the blob afterwards. Any help?

Thanks,

Gary

**Comment by TonyCat** [comment]
Thanks Gary I noticed that it worked out of the box when I used it in Alloy but when when I wrote classic style the honour scale factor is a must to get it to work. Cheers!

**Comment by garycrook** [comment]
No problem :-)
