### ISSUE TITLE
Attempt to invoke virtual method 'void com.google.android.gms.maps.GoogleMap.clear()' 

### ISSUE THREAD

**Issue by onury** [appcelerator-modules/ti.map#154]
I'm working with Android emulators and AFAIK, Google Play services is missing on emulators and map doesn't work.

So I've added conditional code (e.g. `TI_MAP.isGooglePlayServicesAvailable()`) to prevent the app crash. It works unstably and I get the following error when it crashes.

```
[ERROR] TiApplication: (main) [491,1279] Sending event: exception on thread: main msg:java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.GoogleMap.clear()' on a null object reference; Titanium 5.2.1,2016/03/18 22:51,23e1c7d
[ERROR] TiApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.GoogleMap.clear()' on a null object reference
[ERROR] TiApplication: 	at ti.map.TiUIMapView.release(TiUIMapView.java:899)
[ERROR] TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.releaseViews(TiViewProxy.java:539)
[ERROR] TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.releaseViews(TiViewProxy.java:536)
[ERROR] TiApplication: 	at ti.modules.titanium.ui.TabProxy.releaseViews(TabProxy.java:157)
[ERROR] TiApplication: 	at ti.modules.titanium.ui.TabGroupProxy.releaseViews(TabGroupProxy.java:559)
[ERROR] TiApplication: 	at ti.modules.titanium.ui.TabGroupProxy.handleClose(TabGroupProxy.java:429)
[ERROR] TiApplication: 	at org.appcelerator.titanium.proxy.TiWindowProxy.handleMessage(TiWindowProxy.java:109)
[ERROR] TiApplication: 	at ti.modules.titanium.ui.TabGroupProxy.handleMessage(TabGroupProxy.java:117)
[ERROR] TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] TiApplication: 	at android.os.Looper.loop(Looper.java:148)
[ERROR] TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
[ERROR] TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
The stack trace is all Java so I cannot trace the source of this error.

SDK version: 5.2.1.GA
ti.map version: SDK's version and tried the latest 2.3.8

**Comment by ashcoding** [comment]
Just wanna check, are there any other notable modules you are using?
And what version of Android is this crashing on? (I presume this is an emulator?)

**Comment by onury** [comment]
I only use `ti.map` and `ti.cloud`.
This crashes on both Android and Genymotion emulators; (Android 6.0).

**Comment by onury** [comment]
Any news on this issue? Or any hints would be great..

**Comment by asiby** [comment]
Misery love company. Ahahaha. I'm having the same problem.

Somehow, the map object (in java) got released or nullified. This is happening in the release() method of the TiUIMapView object. I'm guessing that if the map object is already null, then there is no point calling map.clear(). So if you know anything about native module development, then try changing the following ...

```
public void release() {
	selectedAnnotation = null;
	map.clear();
	currentCircles = null;
	currentPolygons = null;
	currentPolylines = null;
	map = null;
	timarkers.clear();
	super.release();
}
```

... to this new code ...

```
public void release() {
	selectedAnnotation = null;
	if (map != null) {
		map.clear();
	}
	currentCircles = null;
	currentPolygons = null;
	currentPolylines = null;
	map = null;
	timarkers.clear();
	super.release();
}
```

I am in the process of adding some enhancements to the ti.map module, so I am going trying to try this now and see how it works out.

**Comment by ashcoding** [comment]
@asiby Would appreciate if it becomes a PR eventually. :)

**Comment by asiby** [comment]
Yes. I am counting on it because I have been porting my changes from version to version so far and I think that everyone can benefit from them. Also, it will make my life a little easier. :)

**Comment by onury** [comment]
@asiby Thanks. Yes, I can confirm that this always happens when a `Window` or `TabGroup` containing a map view is closed.

This fix would be greatly appreciated!

**Comment by ashcoding** [comment]
@asiby if it's fine by you, I could do a PR based on what you mentioned here: https://github.com/appcelerator-modules/ti.map/blob/d80899c2f94cc21b825cc9225c5b9760e3c003b8/android/src/ti/map/TiUIMapView.java#L897-L906 Would you prefer me to create a PR? Alternatively, you could submit one and I'll get it reviewed and merged once it's okay.

@onury Could you provide a sample code that could reproduce this crash? Makes it easier to check if the fix will work?

**Comment by asiby** [comment]
This can be closed. Right?

**Comment by onury** [comment]
Yes. With v2.3.10 it does not crash the app anymore 👍 
Thanks!
