### ISSUE TITLE
Crash when starting drag on draggable annotation

### ISSUE THREAD

**Issue by bitfabrikken** [appcelerator-modules/ti.map#161]
Sometimes, when I start dragging an annotation, the app just crashes instantly.
I've debugged a lot, but haven't come up with anything useful.
Hoping someone can help :)

Edit: The crash only occurs when I have added the "pinchangedragstate" eventlistener to the map view.

iOS 9.3 on iPhone 4s, Titanium SDK 5.2.2.GA, ti.map 2.7.0

Here's some info from the Xcode console when the crash occurs:

```
May 13 10:35:39 iPhone mediaserverd[43] <Notice>: '' dk.bitfabrikken.tishadow(pid = 1671) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None
May 13 10:35:39 iPhone SpringBoard[48] <Warning>: HW kbd: Failed to set (null) as keyboard focus
May 13 10:35:39 iPhone com.apple.xpc.launchd[1] (UIKitApplication:dk.bitfabrikken.tishadow[0xa705][1671]) <Notice>: Service exited due to signal: Bus error: 10
May 13 10:35:39 iPhone mediaserverd[43] <Notice>: 'FigPlayer - 1370' (pid = 1370) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None
May 13 10:35:39 iPhone SpringBoard[48] <Warning>: Application 'UIKitApplication:dk.bitfabrikken.tishadow[0xa705]' crashed.
May 13 10:35:39 iPhone UserEventAgent[23] <Warning>: 72763650716501: id=dk.bitfabrikken.tishadow pid=1671, state=0
May 13 10:35:39 iPhone SpringBoard[48] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
May 13 10:35:39 iPhone SpringBoard[48] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
May 13 10:35:39 iPhone ReportCrash[1672] <Error>: assertion failed: 13E233: libsystem_trace.dylib + 15927 [2171E90D-32AA-3F60-9692-C2F8E0D4B1A0]: 0x0
May 13 10:35:39 iPhone Unknown[1672] <Error>: 
May 13 10:35:39 iPhone ReportCrash[1672] <Warning>: os_activity_diagnostic_for_pid() failed!
May 13 10:35:39 iPhone ReportCrash[1672] <Notice>: Formulating report for corpse[1671] TiShadow
May 13 10:35:40 iPhone ReportCrash[1672] <Warning>: Saved type '109(109_TiShadow)' report (17 of max 25) at /var/mobile/Library/Logs/CrashReporter/TiShadow-2016-05-13-103539.ips
```

**Comment by bitfabrikken** [comment]
Closing as I think this is due to running the app in TiShadow .

**Comment by adiscodes** [comment]
I have this issue too and I'm not using TiShadow. Do you still encounter this?

**Comment by designbymind** [comment]
Hi @bitfabrikken,

Would you consider re-opening this issue?

I too am getting an app crash when starting to drag an annotation...

**Environment:**
· Ti SDK 6.0.0.GA
· iOS 9.3/10 (device & simulator)
· ti.map 2.8.0

Thank you!

· Jason 🙂

**Comment by bitfabrikken** [comment]
@designbymind have you tried removing the eventlistener pinchangedragstate from the map, and seeing if it works?

**Comment by designbymind** [comment]
@bitfabrikken — prior to commenting, for some strange reason, I hadn't thought to try that out...

Below are the results I am getting _without_ eventlistener `pinchangedragstate` attached to a ti.map view:

- `draggable:true` property **does** work as expected
- _if_ an eventlistener `click` is attached to the ti.map view:
  - when **beginning** the drag state, e.clicksource returns **map** (and the correct initial e.annotation properties (latitude/longitude) are provided)
  - when **ending** the drag state, e.clicksource returns **pin** (and the new/correct e.annotation properties (latitude/longitude) are provided)

Seems like that 2nd firing of the `click` eventlistener (after the drag has completed) could be considered an unwelcomed one?

**Comment by hansemannn** [comment]
@designbymind Please file a JIRA issue for this if you feel this is incorrect. That's the only way we can schedule and fix your (possible) issue. Thx!

**Comment by hansemannn** [comment]
Fo the map/pin clicksource, it's a native behavior caused by the `mapView:didDeselectAnnotationView:` being called when you start dragging. iOS interprets the gesture gas deselecting the annotation because of the dragging.
