### ISSUE TITLE
mapView.setAnnotations( Array<Modules.Map.Annotation> ) is crashing the application

### ISSUE THREAD

**Issue by deckameron** [appcelerator-modules/ti.map#175]
Appcelerator Studio, build: 4.7.0.201607250649
SDK 5.4.0.GA
Android 6.0.1
Nexus 5

The test code:

```
annotationArray = [];
for (var i in latLon) {
	var point = Map.createAnnotation({
		latitude : latLon[i].lat,
		longitude : latLon[i].lon,
		customView : Titanium.UI.createLabel({
			text : "Some Text",
			color : '#FFF',
			height : 40,
			backgroundImage : '/images/ic_map_marker_dark.png',
			font : {
				fontWeight : 'bold',
				fontSize : 16
			}
		})
	});
	annotationArray.push(point);
}
mapview.setAnnotations(annotationArray); 
```

The Error:

08-23 14:17:23.535: E/AndroidRuntime(6014): FATAL EXCEPTION: main
08-23 14:17:23.535: E/AndroidRuntime(6014): Process: com.company.myapp, PID: 6014
08-23 14:17:23.535: E/AndroidRuntime(6014): java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.maps.model.Marker com.google.android.gms.maps.GoogleMap.addMarker(com.google.android.gms.maps.model.MarkerOptions)' on a null object reference
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at ti.map.TiUIMapView.addAnnotation(TiUIMapView.java:405)
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at ti.map.TiUIMapView.addAnnotations(TiUIMapView.java:416)
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at ti.map.TiUIMapView.updateAnnotations(TiUIMapView.java:425)
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at ti.map.TiUIMapView.propertyChanged(TiUIMapView.java:266)
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at org.appcelerator.kroll.KrollPropertyChange.fireEvent(KrollPropertyChange.java:21)
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1093)
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:357)
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at ti.map.ViewProxy.handleMessage(ViewProxy.java:249)
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at android.os.Handler.dispatchMessage(Handler.java:98)
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at android.os.Looper.loop(Looper.java:148)
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at java.lang.reflect.Method.invoke(Native Method)
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-23 14:17:23.535: E/AndroidRuntime(6014): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by botmaster** [comment]
Same issue -_-

**Comment by hansemannn** [comment]
Please file a JIRA-ticket for this issue, otherwise our team can't schedule it. Thanks!
