### ISSUE TITLE
mapView.leftView and mapView.rightView are not working on Android

### ISSUE THREAD

**Issue by deckameron** [appcelerator-modules/ti.map#176]
It does not raise any error, but the view does not get rendered.

Appcelerator Studio, build: 4.7.0.201607250649
SDK 5.4.0.GA
Android 6.0.1
Nexus 5

Example code:

```
var leftView = Titanium.UI.createView({
    height : 24,
    width : 24,
    backgroundColor : '#DDBB00'
});

var point = Map.createAnnotation({
    title : "Some Title",
    leftView : leftView,
    latitude : -43,
    longitude : -19
});
```

**Comment by hansemannn** [comment]
Please file a JIRA ticket for your issue, then we may schedule it for feature versions or someone from the community can step in. Thx!
