### ISSUE TITLE
Android Google Maps now has styles

### ISSUE THREAD

**Issue by yozef** [appcelerator-modules/ti.map#181]
A lot of people have been waiting for this to be implemented part of Google Maps Android SDK.

We are able to style the Map just like in Web Google Maps.

https://developers.google.com/maps/documentation/android-api/hiding-features

**Comment by m1ga** [comment]
Still have to do some checks and documentation:
https://github.com/appcelerator-modules/ti.map/pull/186

**Comment by hansemannn** [comment]
Will be available in 6.1.0 SDK or right now from the releases tab :-)
