### ISSUE TITLE
Animation Marker

### ISSUE THREAD

**Issue by eolverabea** [appcelerator-modules/ti.map#185]
They may include a method to animate a marker, transitions from point to point, Google API has one, but check the module documentation but found nothing.

**Comment by eolverabea** [comment]
https://developers.google.com/android/reference/com/google/android/gms/maps/Projection

**Comment by hansemannn** [comment]
Please file a JIRA ticket for your feature request, then we may schedule it for feature versions or someone from the community can step in. Thx!
