### ISSUE TITLE
Request: Download of map tiles, and use these when offline (will pay)

### ISSUE THREAD

**Issue by bitfabrikken** [appcelerator-modules/ti.map#191]
I could really use a feature of being able to download tiles for offline usage, and am of course willing to pay for it.

The purpose is for an app, where the users usually don't have a good internet connection, e.g. in the woods or mountain climbing. We're talking rather small areas, so downloading the data on the phone should be feasible. 

From code you would specify a region (latitude, longitude, latitudeDelta, longitudeDelta), and a download would be initiated.  A function to estimate the size of the download would be handy as well, so you could warn the user if it's too large of an area, they're about to download.

Once downloaded, the map should be able to use this data, so there should be a way to manually force this. So it can be used when offline. This means the map itself must also be able to be shown, even though there's no internet connection.

Contact me if you're the right person for the job, or know someone who might be interested - it will of course be added as a pull request so others can benefit as well.

Cheers, Dan

**Comment by hansemannn** [comment]
Please file a JIRA ticket for your feature request, then we may schedule it for feature versions or someone from the community can step in. Thx!
