### ISSUE TITLE
[MOD-2418] Add Annotation Rotation functionality

### ISSUE THREAD

**Issue by yozef** [appcelerator-modules/ti.map#226]
For iOS: There is a `rotation` on the Annotation. Would it be possible to incorporate into ti.map?

There is also the same feature for Android.

**Comment by hansemannn** [comment]
Sounds good! Feel free to submit a pull request for both and we will handle it. 🚀

**Comment by hansemannn** [comment]
@Topener Can you move this to JIRA?

**Comment by Topener** [comment]
Ticket is here: https://jira.appcelerator.org/browse/MOD-2418

**Comment by hansemannn** [comment]
Thanks Rene!
