### ISSUE TITLE
Android : Disable indoor Map

### ISSUE THREAD

**Issue by jerry42** [appcelerator-modules/ti.map#243]
Hello,
Is it possible to add the ability to disable indoor map ? Google is having a problem with indoor map in London, SF and Tokyo which make my app crash.

Disabling indoor map would fix the problem, according to this bug tracker : https://issuetracker.google.com/issues/35829548

Thanks

**Comment by ypbnv** [comment]
Hello! 

I have created a ticket for exposing the API in the module. You can watch there for when it will be included. Here is the link:
https://jira.appcelerator.org/browse/MOD-2457

**Comment by jerry42** [comment]
Thanks @ypbnv I will keep track of the Jira !

**Comment by Topener** [comment]
closing issues to prevent double tracking. Anyone interested in this feature can follow the mentioned jira ticket.
