### ISSUE TITLE
[Android] addPolygon()  - Unable to convert java.util.HashMap

### ISSUE THREAD

**Issue by LilianAlvarez** [appcelerator-modules/ti.map#275]
Hello,

I get this error in a callback of a WebService call. I add a certain number of polygons to the map using this function.
Titanium : sdk 8.2.0.GA
ti.map : 4.3.1 

[ERROR] TiExceptionHandler:       $.map.addPolygon(enhancedMap.area);
[ERROR] TiExceptionHandler:             ^
[ERROR] TiExceptionHandler: Error: Unable to convert java.util.HashMap
[ERROR] TiExceptionHandler:     at Object.createPolygon (/alloy/controllers/common/map.js:1375:13)
[ERROR] TiExceptionHandler:     at Object.createPolygonHuntingArea (/alloy/controllers/common/map.js:1353:23)
[ERROR] TiExceptionHandler:     at /alloy/controllers/common/map.js:1761:27
[ERROR] TiExceptionHandler:     at /ti.cloud/ti.cloud.js:34:176
[ERROR] TiExceptionHandler:     at HTTPClient.onload (/ti.cloud/ti.cloud.js:80:241)
[ERROR] TiExceptionHandler:
[ERROR] TiExceptionHandler:     org.appcelerator.titanium.util.TiConvert.toDouble(TiConvert.java:546)
[ERROR] TiExceptionHandler:     ti.map.PolygonProxy.parseLocation(PolygonProxy.java:319)
[ERROR] TiExceptionHandler:     ti.map.PolygonProxy.addLocation(PolygonProxy.java:150)
[ERROR] TiExceptionHandler:     ti.map.PolygonProxy.processPoints(PolygonProxy.java:167)
[ERROR] TiExceptionHandler:     ti.map.PolygonProxy.processOptions(PolygonProxy.java:121)
[ERROR] TiExceptionHandler:     ti.map.TiUIMapView.addPolygon(TiUIMapView.java:777)
[ERROR] TiExceptionHandler:     ti.map.ViewProxy.handleAddPolygon(ViewProxy.java:774)
[ERROR] TiExceptionHandler:     ti.map.ViewProxy.addPolygon(ViewProxy.java:758)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:75)

**Comment by AppWerft** [comment]
There is no validation of input. Ensure that all parts of points are double/float in in right range (90/180°)

**Comment by m1ga** [comment]
@LilianAlvarez can you show the output of the webservice that is creating that error?

**Comment by AppWerft** [comment]
Currently I'm developing a general import tool for geolocations. https://github.com/AppWerft/ti.map/blob/android_tileoverlay/android/src/ti/map/utils/LatLngArray.java 
This class will use in all other classes that imports `points`.

**Comment by LilianAlvarez** [comment]
Hello guys,
Thank you for you help, it's just my data that was corrupted. Problem fix ! 

Have a nice day !

**Comment by AppWerft** [comment]
The problems:
1. toDouble() throws an exception, this will not catched,
2. new LatLng() aspects valid numbers in right range (180°/90°), this will not tested before
