### ISSUE TITLE
Draggable annotations break if they have a custom image

### ISSUE THREAD

**Issue by bitfabrikken** [appcelerator-modules/ti.map#35]
Annotations with a custom image icon can be dragged fine. But once you scroll the map, it's apparant that the annotation is no longer "stamped" to the map - it's now fixed to wherever you placed it on the screen.

**Comment by hansemannn** [comment]
Hi @bitfabrikken , is this issue still present?

**Comment by hansemannn** [comment]
Closing this issue since we didn't receive further feedback.
