### ISSUE TITLE
Uniform Map.view.longclick() and Map.view.longpress()

### ISSUE THREAD

**Issue by madrobots** [appcelerator-modules/ti.map#41]
According the doc (http://docs.appcelerator.com/titanium/latest/#!/api/Modules.Map.View-event-longclick)

1. longclick() is only for Android and return Lat & Long
2. longpress() has disappeared but can be use in a app. However it return X and Y (pixel) of the map

It would be great to uniform this a little bit.

**Comment by hansemannn** [comment]
@mrlundis Can this issue be closed with the latest release?

**Comment by mrlundis** [comment]
@hansemannn I don't know, we've moved away from the longress/-click interactions. @astjohn Might be in a better position to answer this.

**Comment by astjohn** [comment]
@hansemannn I believe my changes were incorporated and fixed this issue. Feel free to close.

**Comment by hansemannn** [comment]
Nice, thanks!
