### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by faroukmokrani** [appcelerator-modules/ti.map#44]
Hi, thanks for this work , so i want to add a mapView to ScrollView container "multiContainer" like attached image : 
![capture d ecran 2014-05-11 10 31 56](https://cloud.githubusercontent.com/assets/6905578/2938097/4c38b1a8-d8ef-11e3-987b-8e0a5bea650e.png)
but i have a blank map in the container ? what is it ? if i add the mapView in the window i get the mapView correctly .
any solutions for this.
Thanks.

**Comment by hansemannn** [comment]
This should not happen in recent versions of the module, closing!
