### ISSUE TITLE
OutOfMemory Error in 'Google Maps Android API v2' module for Driving direction between long distance

### ISSUE THREAD

**Issue by ghost** [appcelerator-modules/ti.map#6]
I have downloaded Google Maps Android API v2 and using it in my Titanium Project for Android. Map functionality is working fine. But for direction between long distance (say for example from CA to CT) I’m getting OutOfMemory Error. PFA for full log
I/dalvikvm-heap( 6852): Clamp target GC heap from 71.131MB to 64.000MB
D/dalvikvm( 6852): GC_BEFORE_OOM freed 10K, 2% free 64502K/65324K, paused 244ms, total 244ms
E/dalvikvm-heap( 6852): Out of memory on a 353048-byte allocation.
I/dalvikvm( 6852): "main" prio=5 tid=1 RUNNABLE
I/dalvikvm( 6852):   | group="main" sCount=0 dsCount=0 obj=0x415d59a0 self=0x400e5010
I/dalvikvm( 6852):   | sysTid=6852 nice=0 sched=0/0 cgrp=apps handle=1074963420
I/dalvikvm( 6852):   | state=R schedstat=( 49900041000 7079297000 33204 ) utm=4486 stm=504 core=1
I/dalvikvm( 6852):   at java.util.ArrayList.add(ArrayList.java:~114)
I/dalvikvm( 6852):   at com.google.android.gms.maps.model.PolylineOptions.add((null):-1)
I/dalvikvm( 6852):   at ti.map.RouteProxy.addLocation(RouteProxy.java:100)
I/dalvikvm( 6852):   at ti.map.RouteProxy.processPoints(RouteProxy.java:113)
I/dalvikvm( 6852):   at ti.map.RouteProxy.processOptions(RouteProxy.java:80)
I/dalvikvm( 6852):   at ti.map.TiUIMapView.addRoute(TiUIMapView.java:386)
I/dalvikvm( 6852):   at ti.map.ViewProxy.handleAddRoute(ViewProxy.java:360)
I/dalvikvm( 6852):   at ti.map.ViewProxy.handleMessage(ViewProxy.java:128)
I/dalvikvm( 6852):   at android.os.Handler.dispatchMessage(Handler.java:95)
I/dalvikvm( 6852):   at android.os.Looper.loop(Looper.java:137)
I/dalvikvm( 6852):   at android.app.ActivityThread.main(ActivityThread.java:5041)
I/dalvikvm( 6852):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm( 6852):   at java.lang.reflect.Method.invoke(Method.java:511)
I/dalvikvm( 6852):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
I/dalvikvm( 6852):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
I/dalvikvm( 6852):   at dalvik.system.NativeStart.main(Native Method)
Downloaded Google Maps Android API v2 module from below URL.
https://marketplace.appcelerator.com/apps/5005?527725721#support
Looks like issue in ti.map module , Could you please help me to resolve this issue at the earliest?

**Comment by hansemannn** [comment]
The user is not longer on Github so we cannot ask him for additional infos. Closing for now.
