### ISSUE TITLE
Satellite type works fine in iOS but shows nothing in Android

### ISSUE THREAD

**Issue by junerockwell** [appcelerator-modules/ti.map#63]
Hi. I've checked all the requirements for ti.map module and the hybrid, normal, and satellite works fine in iOS but I didn't even do anything special in Android and only the normal one works. The satellite doesn't show anything at all except for route lines and the annotation but no satellite view like street views, etc. I'm using iPhone5s iOS8 and Android HTC One 4.4.2.

**Comment by hansemannn** [comment]
@ashcoding can you validate?

**Comment by hansemannn** [comment]
This should not happen in recent versions of the module, closing!
