### ISSUE TITLE
Android: How to use mapView in a Fragment?

### ISSUE THREAD

**Issue by manumaticx** [appcelerator-modules/ti.map#77]
Hi.
I have this Drawer module [here](https://github.com/manumaticx/Ti.DrawerLayout) which uses a Fragment as the content view. This works actually fine except for the mapView. It'll raise a `ResourceNotFoundException` within the FragmentManager used in `TiUIFragment ` (I guess). You can't really backtrace it. You can see the crash-log in the [according issue](https://github.com/manumaticx/Ti.DrawerLayout/issues/4). I really have no idea how to solve this. Any help is really appreciated. 

P.S. I've also created a simple test app to reproduce this: https://github.com/manumaticx/Ti.DrawerLayout.MapTest

Edit:
I have also created a JIRA ticket for this: [TIMOB-18244](https://jira.appcelerator.org/browse/TIMOB-18244)

**Comment by manumaticx** [comment]
It even crashes when it is not wrapped in another fragment. I've tried an view-only approach with only the layout and no fragments. Same crash. I'm pretty sure this is a bug in the TiUIFragment as it says `android.content.res.Resources$NotFoundException: Unable to find resource ID #0x3e8` and this is the id given here: https://github.com/appcelerator/titanium_mobile/blob/master/android/titanium/src/java/org/appcelerator/titanium/view/TiUIFragment.java#L17
Why can't the id be resolved? Is it a timing problem? Does it try to access it before it's initialized? I don't get my head around this. Please help :pray:

**Comment by muka** [comment]
Hi, I've noticed that this happens randomly in tab groups with the same message. 

As a work around (it is reported in the appcelerator jira too, somewhere) is to add the mapView instance to the container on the `open` or `focus` event. 
See https://developer.appcelerator.com/question/151567/google-maps-v2-module-crashes-when-view-placed-in-tab-group
But it won't fix it, just works most of the time

**Comment by john-dalsgaard** [comment]
+1

I am hit by the same issue. Trying to find a drawer implementation where it is not an issue - so far no luck.... - and the customer scratching on the door.... :-(

**Comment by tvfoodmaps** [comment]
This issue is effecting me as well, anyone have an update?

**Comment by manumaticx** [comment]
Closing this. Regarding Ti.DrawerLayout this was solved in [#19](https://github.com/manumaticx/Ti.DrawerLayout/pull/19) and [#36](https://github.com/manumaticx/Ti.DrawerLayout/pull/36).

**Comment by kratosmat** [comment]
Hi all,
I am a bit confused.
I am using nl.fokkezb.drawer on a view where is a MapView (module=ti.map) and it isn't able to show the map, with the following error 

TiUIMapView: (main) [7,17756] Unable to load map

Furthermore, I am using SDK 4.1.0.GA.

I haven't understood if this is a bug, if it was solved or not.

Thanks in advance,
Matteo.

**Comment by manumaticx** [comment]
@kratosmat it's not a real ti.map bug - the issue was solved in Ti.DrawerLayout (which also works with nl.fokkezb.drawer) but not yet in the NappDrawer
