### ISSUE TITLE
Add support for polylines and polygon

### ISSUE THREAD

**Issue by muka** [appcelerator-modules/ti.map#9]
Hi, 
I've added support for polylines and polygon in my fork 
https://github.com/muka/ti.map/tree/master/android/src/ti/map

Hope could be merged in the main repository.

Regards

**Comment by mikedias** [comment]
:+1:

**Comment by astjohn** [comment]
@mikedias - We currently have a branch that you might want to check out that is more or less in stable condition. 

https://github.com/Sitata/ti.map/tree/drawing_longpress_fix_ios

This branch add drawing support, but also:
- Fixed the longpress event on iOS.
- Fixed the fact that the "region" property was not updating on android during map pan events as iOS does.
- Added dependency on 3.5.0.GA for ios8/64bit support.

I did notice that with 3.5.0.GA, @muka's click additions to shapes on Android no longer works. He's aware and working on a fix. Then I think we'll be ready to pull this into appcelerator if they accept it.

**Comment by mikedias** [comment]
Hi @astjohn, thank you for the tip! I hope to see this branch in the official releases soon!

**Comment by muka** [comment]
@astjohn all good from my side! 

For some obscure reasons using JSON.stringify / console.log to serialize the event object from the click callback seems to freeze the execution context (probably due to some kind of recursion?) 
If there is a feedback on this I'll be happy to investigate further

master branch in https://github.com/muka/ti.map is up to date
If there are no more issues, :+1:  to proceed!

**Comment by yozef** [comment]
@muka Works nicely :)

**Comment by astjohn** [comment]
@muka, Thanks. Will be submitting now. Sorry it took me so long to finally wrap this up.
