### ISSUE TITLE
Map cluster

### ISSUE THREAD

**Issue by ankesh27** [appcelerator-modules/ti.map#90]
Does the IOS version supports Map clustering? If yes, How?

**Comment by hansemannn** [comment]
As far as I know, Clustering is not supported, yet.

**Comment by ankesh27** [comment]
Okay, any other module that supports clustering ? (a google map module may be).

**Comment by hansemannn** [comment]
There is a google maps module available in the Appcelerator Marketplace and an open source module is currently in progress in the community.
