### ISSUE TITLE
ti.map module does not support version 2.3.0 for android on titanium sdk

### ISSUE THREAD

**Issue by edelkevis** [appcelerator-modules/ti.map#92]
I tries to include module and i get this message in tía.XML

ti.map module does not support version 2.3.0 for android on titanium sdk,

**Comment by hansemannn** [comment]
@edelkevis Does it work with the latest ti.map android version ([2.3.4](https://github.com/appcelerator-modules/ti.map/releases/tag/android-2.3.4)) ?
