### ISSUE TITLE
Version 2.2.2 iOS 7 App Crash

### ISSUE THREAD

**Issue by dlewis23** [appcelerator-modules/ti.map#95]
I've noticed now that version 2.2.2 of the iOS Maps module with cause my app to crash only on a iPad running iOS 7. On iOS 8 it works perfect no issues at all. If I change the map module down to 2.2.0 It works no problem the issue goes away. 

I get this error:

[ERROR] :  The application has crashed with an uncaught exception 'NSInvalidArgumentException'.
[ERROR] :  Reason:
[ERROR] :  -[TiUIImageView setPreservesSuperviewLayoutMargins:]: unrecognized selector sent to instance 0x1a2f8e30
[ERROR] :  Stack trace:
[ERROR] :  
[ERROR] :  0   CoreFoundation                      0x2e8c2fd3 <redacted> + 130
[ERROR] :  1   libobjc.A.dylib                     0x3948accf objc_exception_throw + 38
[ERROR] :  2   CoreFoundation                      0x2e8c6967 <redacted> + 202
[ERROR] :  3   CoreFoundation                      0x2e8c5253 <redacted> + 706
[ERROR] :  4   CoreFoundation                      0x2e8147f8 _CF_forwarding_prep_0 + 24
[ERROR] :  5   MyAPP                          0x0060760d MyAPP + 5551629
[ERROR] :  6   MyAPP                          0x0060fb07 MyAPP + 5585671
[ERROR] :  7   MapKit                              0x2fa9fef3 <redacted> + 350
[ERROR] :  8   MapKit                              0x2fa6393d <redacted> + 412
[ERROR] :  9   MapKit                              0x2fa6231f <redacted> + 1218
[ERROR] :  10  Foundation                          0x2f2acb05 __NSFireTimer + 64
[ERROR] :  11  CoreFoundation                      0x2e88e1b7 <redacted> + 14
[ERROR] :  12  CoreFoundation                      0x2e88ddcf <redacted> + 782
[ERROR] :  13  CoreFoundation                      0x2e88c16b <redacted> + 1210
[ERROR] :  14  CoreFoundation                      0x2e7f6f4f CFRunLoopRunSpecific + 522
[ERROR] :  15  CoreFoundation                      0x2e7f6d33 CFRunLoopRunInMode + 106
[ERROR] :  16  GraphicsServices                    0x3371c663 GSEventRunModal + 138
[ERROR] :  17  UIKit                               0x3114216d UIApplicationMain + 1136
[ERROR] :  18  MyAPP                          0x000c1153 MyAPP + 20819
[ERROR] :  19  libdyld.dylib                       0x39997ab7 <redacted> + 2
[ERROR] :  *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TiUIImageView setPreservesSuperviewLayoutMargins:]: unrecognized selector sent to instance 0x1a2f8e30'
[ERROR] :  *** First throw call stack:
[ERROR] :  (0x2e8c2fd3 0x3948accf 0x2e8c6967 0x2e8c5253 0x2e8147f8 0x60760d 0x60fb07 0x2fa9fef3 0x2fa6393d 0x2fa6231f 0x2f2acb05 0x2e88e1b7 0x2e88ddcf 0x2e88c16b 0x2e7f6f4f 0x2e7f6d33 0x3371c663 0x3114216d 0xc1153 0x39997ab7)
-- End application log -------------------------------------------------------

**Comment by hansemannn** [comment]
Fixed in recent versions of the iOS module.
